repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.59.0  # Use the latest version or specify a version
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
    additional_dependencies:
      - "terraform-docs>=0.18.0"